Add context menu on clicking inline channel name
thelounge/thelounge pull request #4376
Opened 2021-11-27 15:20 UTC by sfan5

Maybe that's just me but clicking on a `#channel` instantly joining it is unexpected.
This also often happens to me when I'm trying to select text adjacent to a channel name, or rather what The Lounge believes to be a channel name (such as github issue numbers).

This PR replaces the click-to-join with a context menu that either offers jumping to the already open channel *or* joining it:
![grafik](https://user-images.githubusercontent.com/1042418/143687088-3646e546-bb3e-43c4-803f-892c655ca1f4.png)

2021-11-27 22:23 UTC, MaxLeiter requested changes

2021-11-27 22:23 UTC, MaxLeiter commented on client/js/helpers/contextMenu.js
> +	if (channel) {
I would rather `return [{ }]` twice than have the single return and the `items = []` declaration.

2021-11-28 08:32 UTC, itsjohncs approved these changes
LGTM

2021-11-29 22:41 UTC, MaxLeiter approved these changes

2021-11-29 23:34 UTC, MaxLeiter commented
I shared these two screenshots on IRC and while I prefer the second (with a centered `+`) people seem to prefer the current alignment. 
before:
<img width="232" alt="Screen Shot 2021-11-29 at 3 23 24 PM" src="https://user-images.githubusercontent.com/8675906/143959354-d2668e6c-823f-4f7f-aa36-2d0533b0a7ba.png">
after:
<img width="235" alt="Screen Shot 2021-11-29 at 3 22 57 PM" src="https://user-images.githubusercontent.com/8675906/143959358-e7c8528e-b15c-4ff0-b4e7-dc8816a11ce1.png">

2021-11-29 23:35 UTC, merged