Vue3 Upgrade
thelounge/thelounge pull request #4474
Opened 2022-02-13 05:28 UTC by sha1sum

This upgrades to Vue 3 with all the accompanying changes necessary.

2022-02-13 05:57 UTC, MaxLeiter commented
@xPaw tagging you here in case you wanted to take a look because I know you were at one point working on this

2022-02-13 15:37 UTC, xPaw commented
Well my old branch is still up at https://github.com/thelounge/thelounge/tree/vue3 if you want to take a look whether anything was different on it.

2022-02-14 04:36 UTC, sha1sum commented
@MaxLeiter @xPaw we are ready to go! This obviously deserves a pull down and check for yourselves, but in my opinion, LGTM 👍

2022-02-14 04:42 UTC, MaxLeiter requested changes

2022-02-14 04:42 UTC, MaxLeiter commented on webpack.config-test.js
> +		__VUE_OPTIONS_API__: JSON.stringify(true),
I think I'd prefer to just hard code "true" or "false" here and avoid the JSON call

2022-02-14 04:42 UTC, MaxLeiter commented on webpack.config.js
> +		new webpack.DefinePlugin({
Same as last comment re JSON.stringify

2022-02-14 05:03 UTC, sha1sum reviewed
The back button seems to not be functioning properly. I will look into this.

2022-02-14 22:16 UTC, MaxLeiter commented on client/components/App.vue
> +	setup() {
Can we and do we want to use https://vuejs.org/api/sfc-script-setup.html#script-setup?

2022-02-15 09:19 UTC, xPaw commented on client/components/InlineChannel.vue
> +	template: `
Why the duplicated templated?

2022-02-15 09:21 UTC, xPaw commented on client/components/Username.vue
> +	template: `<span
Duplicate template here too.

2022-02-15 09:23 UTC, xPaw commented on client/js/helpers/parse.js
> -	const userModes = network?.serverOptions?.PREFIX.symbols || ["!", "@", "%", "+"];
Is this change necessary? `network?.` should be same as doing `network ? network...`

2022-02-15 09:24 UTC, xPaw commented on client/js/router.js
> +	if (!router.app.$refs) {
Looks suspicious

2022-02-15 09:28 UTC, xPaw commented on client/components/MessageTypes/whois.vue
> +				<div v-for="special in message.whois.special" :key="special">
`div` is not necessary here, is it?

2022-02-15 09:30 UTC, xPaw commented
In my branch I had to change v-slot for RevealPassword, is that no longer necessary? https://github.com/thelounge/thelounge/commit/2f8f7e76336c4f37b336e2d892c80ec9e23417c0

2022-04-12 01:04 UTC, MaxLeiter commented
hey @sha1sum, are you still interested in taking this on? Now that 4.3.1 is out we can review + merge this if you can address our comments

2022-05-31 03:29 UTC, MaxLeiter commented
Thanks for your efforts here @sha1sum! I’ve included some of your changes in #4559 and will be sure to credit you in the changelog / release notes 🙏

2022-05-31 03:29 UTC, closed without merging

2022-05-31 04:17 UTC, sha1sum commented
@MaxLeiter I really appreciate that. I somehow completely missed your question a couple of months ago (GitHub notifications can be noisy). Sorry about that. I hope that some of this helped!