Add changelog for 4.4.0
thelounge/thelounge pull request #4722
Opened 2023-04-22 07:52 UTC by brunnre8

2023-04-25 06:53 UTC, MaxLeiter requested changes
left a bunch of nitpicks, the rest LGTM.

2023-04-25 06:53 UTC, MaxLeiter commented on CHANGELOG.md
> +This is mostly a developer focused release. Max, Eric and others rewrote the whole thing in typescript / vue3,
```suggestion
This is mostly a developer focused release. Max, Eric and others rewrote the whole thing in TypeScript / Vue 3,
```

2023-04-25 06:53 UTC, MaxLeiter commented on CHANGELOG.md
> +Following the nodejs maintenance schedule, The Lounge now needs at least node 14 to run.
```suggestion
Following the Node.js maintenance schedule, The Lounge now needs at least Node.js 14 to run.
```

2023-04-25 06:53 UTC, MaxLeiter commented on CHANGELOG.md
> +A huge thanks to everyone who contributed in any way to this release, your help is much appreciated.
```suggestion
A big thanks to everyone who contributed in any way to this release, your help is much appreciated.
```

you use `huge` earlier

2023-04-25 06:53 UTC, MaxLeiter commented on CHANGELOG.md
> +Settings are now grouped and hopefully easier to navigate for new users.
```suggestion
Settings are now grouped and easier to navigate for new users.
```

2023-04-25 06:53 UTC, MaxLeiter commented on CHANGELOG.md
> +Packagers: Considering the switch to Typescript, the server build now emits to the dist/ folder.
```suggestion
Packagers: Considering the switch to TypeScript, the server build now emits to the dist/ folder.  
```

2023-04-25 20:40 UTC, brunnre8 commented
note to self: add xpaw's provenance + lenore's bug fix

2023-04-29 11:55 UTC, brunnre8 commented
we're now up to date with master, might want to wait for #4728 then do an RC

2023-05-06 08:59 UTC, merged