Prune old events from sqlite database
thelounge/thelounge pull request #4737
Opened 2023-05-17 16:45 UTC by azeemba

Adds a new config `dbHistoryDays` which defaults to undefined.

At start up, each database handler reads the config. If the value is set, then a reoccuring task is scheduled to clean up old events. Events older than `dbHistoryDays` are targeted but only a few thousand events are cleaned up per iteration to avoid freezing the server.

Adds unit tests to validate the cleanup logic as well.

Fixes #2822

2023-05-18 15:46 UTC, brunnre8 requested changes
Thanks a lot for taking this on.
Now, I've some general comments as to how I think this could work, plus a few minor comments in the code directly.

I think this is a bit too limited as is.
For starters, I want the history retention to be configurable by the user, not just the admin.
While in many cases that's the same, it isn't in all cases and not having to edit the server config for something like that is better.

What that means is that we need this to be a hierarchical configuration. Admins sets global limits as they see fit, user can lower that limit as they feel like.

We should also put that configuration into its own top level config object so that we can add more related settings in the future, for instance I would like to add the ability to only delete unimportant status messages (leave, part, nick change, away, back etc) while retaining the actual useful stuff indefinitely (privmsg, notice).

Does this make sense?

Also note, you should probably rebase on top of https://github.com/thelounge/thelounge/pull/4718 as I'll merge that soon (after a bugfix release for 4.4.0)

2023-05-19 08:08 UTC, fnutt commented
> I think this is a bit too limited as is. For starters, I want the history retention to be configurable by the user, not just the admin. While in many cases that's the same, it isn't in all cases and not having to edit the server config for something like that is better.
> 
> What that means is that we need this to be a hierarchical configuration. Admins sets global limits as they see fit, user can lower that limit as they feel like.

I'm not sure why a user would set it lower than the admin global limit. What is the usecase for this?

2023-05-19 11:02 UTC, brunnre8 commented
Admin says, yeah well, storage isn't an issue.
User says, out of privacy issues I'm uncomfortable to have history there for longer than a month.

Easy enough to imagine, no?

2023-07-15 09:45 UTC, brunnre8 requested changes
Thanks for the update.
In my opinion this should still be restructured a bit though, tell me if you disagree with my comments and I try to explain my reasoning a bit better.

2023-07-15 09:45 UTC, brunnre8 commented on server/plugins/messageStorage/sqlite.ts
> +	mergeClientConfig(clientStorageConfig: SqliteConfig) {
This isn't the right place for that kind of logic.
The config needs to be merged by the core code, not the sqlite specific storage backend.

Yes, currently sqlite is our only implementation of the interface, but that doesn't mean that we should violate the layers.

2023-07-15 09:45 UTC, brunnre8 commented on server/config.ts
> +
that type seems odd to me?

You shouldn't set that to an object or undefined, things that want it optional shall say so when they mean it.

Meaning, the user of the type should do 
```typescript
export type ConfigType = {
 // ...
sqliteConfig?: SqliteConfig;
// ...
}
```
Or whatever, but not that funny type that is intrinsically this way.
That's a hassle to use

2023-07-15 09:45 UTC, brunnre8 commented on defaults/config.js
> +	// 		Undefined/-1/0 is treated an unlimited.
exactly undefined
We should have one way and only one way of configuring something.

2023-07-15 09:45 UTC, brunnre8 commented on test/plugins/sqlite.ts
> +		store = new MessageStorage("testUser", undefined as any);
such casts are very brittle... if you can avoid so please do and in this case you trivially could by providing a correct default value

2023-07-16 15:36 UTC, azeemba commented
I appreciate the feedback but this has slipped in priority for me. Happy for someone to take over the PR or to close the PR.

2023-07-16 20:03 UTC, brunnre8 commented
thanks for your efforts

2023-11-04 10:49 UTC, closed without merging