Added a channel (or network) toggle to notify on all messages
thelounge/thelounge pull request #4779
Opened 2023-09-02 20:43 UTC by antoniomika

This PR adds a toggle on channels (or networks) to notify on all messages. 

<img width="265" alt="image" src="https://github.com/thelounge/thelounge/assets/6239308/8857fd26-8f8a-4823-9a70-8f5fb7c1806c">
and 
<img width="297" alt="image" src="https://github.com/thelounge/thelounge/assets/6239308/1009f1af-b628-4d66-a2c6-3fc9a0fe6ac8">

I probably should've asked for comment on what to use for the icon and toggle text. As of now, the icon is [volume-up](ttps://fontawesome.com/v5.15/icons/volume-up?style=solid) and the text is:

When all notifications enabled:
```
Don't notify on all messages for ${chanType}
```

When all notifications disabled:
```
Notify on all messages for ${chanType}
```

`${chanType}` is either `channel` or `network`.

2023-09-19 18:44 UTC, brunnre8 requested changes
Thanks a lot for taking this on, much appreciated.

Now... I do think we've outlived the context menu a bit for notification settings. Adding another option makes it too long in my opinion.
Plus the text makes it... somewhat huge don't you think?

I think it'll be better to actually create a UI for those kinds of things that can then also hold other channel specific stuff.

Then... you pretty much copied the muted code, but without deduplicating anything even though all that changes is an event and a field. Maybe this could be improved a bit?

Last, you notify on way too many things. Don't think status messages and such are really something you need a push notification off. What was your reasoning behind this, other than the literal interpretation of "all"?

2023-09-19 18:44 UTC, brunnre8 commented on client/js/socket-events/msg.ts
> +		channel.notifyAll ||
This triggers on way too many things no?

Do you *really* want a notification on every single join / away / topic / mode and what have you?

2023-09-19 18:44 UTC, brunnre8 commented on server/plugins/irc-events/message.ts
> +			(msg.highlight || chan.notifyAll) &&
This conditional was already somewhat large and I think by now we need to structure this a bit differently, or at the very least pull that out into its own function.

We have pretty much a similar conditional up in the socket events

2023-09-19 18:44 UTC, brunnre8 commented on server/server.ts
> +			client.save();
Hrm... considering that this function is more or less exactly the muted one... can we clean this up ?

2023-09-20 16:22 UTC, antoniomika commented
I'll look into what the UX could look like for adding it to the `notifications` part of settings.

My desire was that if someone want's all of the notifications, they want _all_ of the notifications pertaining to the model. We could probably make this more modular, but as you've stated there currently isn't a great place for that to be handled.

Regarding dedupe between this and mute, both features effective do the same thing. We could probably thing of a more general way to add a "toggle" to a specific model. I can look into what that'd look like as well. 

Appreciate the review!

2024-01-18 19:22 UTC, closed without merging